// ===============================================================================
// Unity Autogenerated Live Services Wrapper
//
//                                  DO NOT EDIT
//                                 AUTOGENERATED
//
// This file was generated to help you call your live service events from C#
// ===============================================================================

using System;
using System.Text;

namespace DataPlatform
{
	public class XDP_COTSG_Events
	{
        public static void SetAchiev(string eventName, string UserId, ref Guid PlayerSessionId, float CompletionPercent, float LocationX, float LocationY, float LocationZ)
        {
            DataPlatform.DynamicEvent evt = new DataPlatform.DynamicEvent(eventName);
            evt.AddParamUnicodeString(eventName, UserId);
            evt.AddParamGUID(eventName, PlayerSessionId);
            evt.Send();
        }

        public static void SetHeroStat(string eventName, string UserId, ref Guid PlayerSessionId, int CompletionPercent)
        {
            DataPlatform.DynamicEvent evt = new DataPlatform.DynamicEvent(eventName);
            evt.AddParamUnicodeString(eventName, UserId);
            evt.AddParamGUID(eventName, PlayerSessionId);
            evt.AddParamInt32(eventName, CompletionPercent);
            evt.Send();
        }

        public static void SetHeroStat(string eventName, string UserId, ref Guid PlayerSessionId)
        {
            DataPlatform.DynamicEvent evt = new DataPlatform.DynamicEvent(eventName);
            evt.AddParamUnicodeString(eventName, UserId);
            evt.AddParamGUID(eventName, PlayerSessionId);
            evt.Send();
        }

        public static void SetGameProgress(string UserId, ref Guid PlayerSessionId, float CompletionPercent, float LocationX, float LocationY, float LocationZ)
        {
            DataPlatform.DynamicEvent evt = new DataPlatform.DynamicEvent("GameProgress");
            evt.AddParamUnicodeString("GameProgress", UserId);
            evt.AddParamGUID("GameProgress", PlayerSessionId);
            evt.AddParamFloat("GameProgress", CompletionPercent);
            evt.Send();
        }


    } // end class Events
} // end namespace DataPlatform

